# Generated by Django 5.0.3 on 2024-04-23 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contestant_project', '0003_contestantproject_description_and_more'),
        ('evaluation', '0002_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('project_file_structure', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judges', models.ManyToManyField(blank=True, related_name='event_judges', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organisation_admin', to='user.organisation')),
                ('projects', models.ManyToManyField(blank=True, related_name='event_projects', to='contestant_project.contestantproject')),
                ('rubrics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_event', to='evaluation.rubric')),
                ('sponsors', models.ManyToManyField(blank=True, related_name='sponsored_event', to='user.organisation')),
            ],
        ),
    ]
