# Generated by Django 5.0.3 on 2024-04-18 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0003_alter_evaluation_rubrics'),
        ('event', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organisation_admin', to='user.organisation'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='rubrics',
        ),
        migrations.AddField(
            model_name='event',
            name='rubrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric_event', to='evaluation.rubric'),
        ),
    ]
