# Generated by Django 5.0.3 on 2024-04-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_judges'),
        ('user', '0002_remove_organisation_sponsored_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='sponsored_event', to='user.organisation'),
        ),
    ]
