# Generated by Django 5.0.3 on 2024-04-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant_project', '0005_contestantproject_evaluations_and_more'),
        ('evaluation', '0002_initial'),
        ('event', '0004_event_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='event_projects', to='contestant_project.contestantproject'),
        ),
        migrations.AddField(
            model_name='event',
            name='rubrics',
            field=models.ManyToManyField(blank=True, related_name='rubric_event', to='evaluation.rubric'),
        ),
    ]
