# Generated by Django 5.0.3 on 2024-04-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_projects_event_rubrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='project_file_structure',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
