# Generated by Django 5.0.3 on 2024-04-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('outdated', 'Outdated')], default='active', max_length=100),
        ),
    ]
