# Generated by Django 5.0.3 on 2024-04-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='sponsored_event',
        ),
    ]
