# Generated by Django 5.0.3 on 2024-04-25 14:51

import contestant_project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestantProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('project_logo', models.ImageField(blank=True, null=True, upload_to=contestant_project.models.project_directory_path, verbose_name='logo')),
            ],
        ),
    ]
