# Generated by Django 5.0.3 on 2024-04-22 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contestant_project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contestantproject',
            name='contestants',
            field=models.ManyToManyField(blank=True, related_name='user_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
