# Generated by Django 5.0.3 on 2024-04-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contestant_project', '0001_initial'),
        ('evaluation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestantproject',
            name='evaluations',
            field=models.ManyToManyField(blank=True, related_name='evaluation', to='evaluation.evaluation'),
        ),
    ]
