# Generated by Django 5.0.3 on 2024-04-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant_project', '0002_contestantproject_events'),
        ('evaluation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestantproject',
            name='evaluations',
            field=models.ManyToManyField(blank=True, related_name='evaluation', to='evaluation.evaluation'),
        ),
    ]
