# Generated by Django 5.0.3 on 2024-04-18 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant_project', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestantproject',
            name='users',
        ),
        migrations.AddField(
            model_name='contestantproject',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
