# Generated by Django 5.0.3 on 2024-04-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestant_project', '0003_contestantproject_evaluations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestantproject',
            name='evaluations',
        ),
        migrations.RemoveField(
            model_name='contestantproject',
            name='events',
        ),
    ]
