# Generated by Django 5.0.3 on 2024-04-18 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant_project', '0004_remove_contestantproject_evaluations_and_more'),
        ('evaluation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contestantproject',
            name='evaluations',
            field=models.ManyToManyField(blank=True, related_name='evaluation', to='evaluation.evaluation'),
        ),
        migrations.AddField(
            model_name='contestantproject',
            name='users',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
