# Generated by Django 5.0.3 on 2024-04-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant_project', '0004_remove_contestantproject_users_and_more'),
        ('evaluation', '0003_alter_evaluation_rubrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestantproject',
            name='evaluations',
            field=models.ManyToManyField(blank=True, related_name='evaluation_projects', to='evaluation.evaluation'),
        ),
    ]
