# Generated by Django 5.0.3 on 2024-04-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestant_project', '0006_remove_contestantproject_evaluations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestantproject',
            old_name='users',
            new_name='contestants',
        ),
    ]
